# Generated by Django 2.0.4 on 2018-04-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbranches',
            options={'managed': True},
        ),
    ]
